### ISSUE TITLE
Crash after "Login procedure started"

### ISSUE THREAD

**Issue by iDexe** [PokemonGoF/PokemonGo-Bot-Desktop#101]
Bot is crashing.
### Expected Behavior

Before my last pull everything worked fine.
### Actual Behavior

After logging in ("login procedure started") the App crashes and comes back to the start screen.
### Steps to Reproduce

Happens to me every time. I cloned a fresh directory to make sure its not related to the config file. Also i tried different PTC accounts.
npm version: 3.10.3
node version: 6.3.1
Python version: 2.7.10
pgoapi version: 1.1.6
### Information
- OS
  Mac OS 10.11.6 El Capitan
- Git commit ( to get git commit run `git log -1 --format="%H"`)
  584782fa1425e19ff9d94d16728d95781ade3312
- App's logs

```
nilss-mac-mini:PokemonGo-Bot-Desktop-2 nils$ npm start
> PokemonGoBot@0.0.1-alpha start /Users/nils/Documents/PokemonGO/PokemonGo-Bot-Desktop-2
> electron main.js

GVA info: Successfully connected to the Intel plugin, offline Gen6 
Starting Python process...
Bot path: /Users/nils/Documents/PokemonGO/PokemonGo-Bot-Desktop-2/gofbot
python ./pokecli.py
Python: 2016-08-10 16:26:09,198 [       cli] [INFO] PokemonGO Bot v1.0

Python: 2016-08-10 16:26:09,200 [       cli] [INFO] No config argument specified, checking for /configs/config.json

Python: 2016-08-10 16:26:09,202 [       cli] [INFO] Configuration initialized

Python: 2016-08-10 16:26:09,202 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
2016-08-10 16:26:09,203 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics

Python: 2016-08-10 16:26:09,632 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com

Python: 2016-08-10 16:26:09,678 [PokemonGoBot] [INFO] [set_start_location] Setting start location.

Python: 2016-08-10 16:26:09,679 [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.

Python: 2016-08-10 16:26:09,679 [PokemonGoBot] [INFO] [location_found] Location found: 52.366857, 9.737020 (52.366857, 9.73702, 0.0)

Python: 2016-08-10 16:26:09,680 [PokemonGoBot] [INFO] [position_update] Now at (52.366857, 9.73702, 0)

Python: 2016-08-10 16:26:09,680 [PokemonGoBot] [INFO] [login_started] Login procedure started.

Python: Traceback (most recent call last):
  File "./pokecli.py", line 522, in <module>

Python:     main()
  File "./pokecli.py", line 138, in main
    report_summary(bot)

Python:   File "./pokecli.py", line 147, in report_summary
    metrics.capture_stats()

Python:   File "/Users/nils/Documents/PokemonGO/PokemonGo-Bot-Desktop-2/gofbot/pokemongo_bot/metrics.py", line 73, in capture_stats
    request = self.bot.api.create_request()
  File "/Users/nils/Documents/PokemonGO/PokemonGo-Bot-Desktop-2/gofbot/pokemongo_bot/api_wrapper.py", line 27, in create_request
    self._position_alt
  File "/Users/nils/Documents/PokemonGO/PokemonGo-Bot-Desktop-2/gofbot/pokemongo_bot/api_wrapper.py", line 43, in __init__

Python: PGoApiRequest.__init__(self, *args)
TypeError: __init__() takes exactly 6 arguments (5 given)

Python: Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds

Python: Press Ctrl-C to quit

Bot exited
```

**Comment by austinxw** [comment]
Same issue

> PokemonGoBot@0.0.1-alpha start /Users/Ding/Documents/pokemon/PokemonGo-Bot-Desktop
> electron main.js

Starting Python process...
Bot path: /Users/Ding/Documents/pokemon/PokemonGo-Bot-Desktop/gofbot
python ./pokecli.py
Python: 2016-08-10 21:05:11,282 [       cli] [INFO] PokemonGO Bot v1.0

Python: 2016-08-10 21:05:11,285 [       cli] [INFO] No config argument specified, checking for /configs/config.json

Python: 2016-08-10 21:05:11,292 [       cli] [INFO] Configuration initialized

Python: 2016-08-10 21:05:11,292 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:

Python: 2016-08-10 21:05:11,294 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics

Python: 2016-08-10 21:05:11,313 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com

Python: 2016-08-10 21:05:11,782 [PokemonGoBot] [INFO] [set_start_location] Setting start location.

Python: Traceback (most recent call last):
  File "./pokecli.py", line 522, in <module>

Python:     main()
  File "./pokecli.py", line 138, in main
    report_summary(bot)
  File "./pokecli.py", line 147, in report_summary

Python:     metrics.capture_stats()
  File "/Users/Ding/Documents/pokemon/PokemonGo-Bot-Desktop/gofbot/pokemongo_bot/metrics.py", line 73, in capture_stats
    request = self.bot.api.create_request()
  File "/Users/Ding/Documents/pokemon/PokemonGo-Bot-Desktop/gofbot/pokemongo_bot/api_wrapper.py", line 27, in create_request
    self._position_alt
  File "/Users/Ding/Documents/pokemon/PokemonGo-Bot-Desktop/gofbot/pokemongo_bot/api_wrapper.py", line 43, in __init__

Python:     PGoApiRequest.**init**(self, *args)
TypeError: **init**() takes exactly 6 arguments (5 given)

Python: Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds

Python: Press Ctrl-C to quit

Bot exited
