### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by ghost** [PokemonGoF/PokemonGo-Bot-Desktop#144]
_Issue without proper information won't be answered_
### Expected Behavior

I want bot to START
### Actual Behavior

$-MacBook-Pro:pokemongo-bot$ ./run.sh
Traceback (most recent call last):
  File "pokecli.py", line 41, in <module>
    from pokemongo_bot import PokemonGoBot, TreeConfigBuilder
  File "/Users/$/PokemonGo-Bot/pokemongo_bot/**init**.py", line 19, in <module>
    import cell_workers
  File "/Users/$/PokemonGo-Bot/pokemongo_bot/cell_workers/**init**.py", line 3, in <module>
    from catch_lured_pokemon import CatchLuredPokemon
  File "/Users/$/PokemonGo-Bot/pokemongo_bot/cell_workers/catch_lured_pokemon.py", line 8, in <module>
    from pokemongo_bot.cell_workers.pokemon_catch_worker import PokemonCatchWorker
  File "/Users/$/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 306
    <<<<<<< HEAD
     ^
SyntaxError: invalid syntax
Thu Aug 11 18:18:10 PDT 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.
### Steps to Reproduce

./run.sh
### Information
- OS Yosemite 10.10.5
- Git commit ( to get git commit run `git log -1 --format="%H"`)
- App's logs

**Comment by ProjectBarks** [comment]
We dont have run.sh..... You might be on the wrong branch.... Checkout [PokemonGoF-Bot](https://github.com/PokemonGoF/PokemonGo-Bot)
