### ISSUE TITLE
Application fails if google-analytics is blocked

### ISSUE THREAD

**Issue by jfbethlehem** [PokemonGoF/PokemonGo-Bot-Desktop#158]
_Issue without proper information won't be answered_
### Expected Behaviour

Keeps on going
### Actual Behaviour

Crashes with many obscure error messages, goes back to login screen
### Steps to Reproduce

install, run with network-wide adblocked (pihole)
### Logs:

 npm start

> PokemonGoBot@0.0.1-alpha start /Users/jfbethlehem/Code/Git/PokemonGo-Bot-Desktop
> gulp run

(node:52217) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:52217) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:52217) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[13:29:38] Using gulpfile ~/Code/Git/PokemonGo-Bot-Desktop/gulpfile.js
[13:29:38] Starting 'run'...
[13:29:38] Finished 'run' after 2.39 ms
[2016-08-12T11:29:38.232Z] [electron-connect] [server] started electron process: 52218
[2016-08-12T11:29:38.232Z] [electron-connect] [server] created and listening on 30080
[2016-08-12T11:29:39.345Z] [electron-connect] [server] client (window_id: 1) started.
[2016-08-12T11:29:39.385Z] [electron-connect] [server] receive message from client(window_id: 1) {"type":"initBounds","data":{"bounds":{"x":200,"y":143,"width":1280,"height":720}}}
[2016-08-12T11:29:39.387Z] [electron-connect] [server] receive message from client(window_id: 1) {"type":"getBounds"}
Starting Python process...
Bot path: /Users/jfbethlehem/Code/Git/PokemonGo-Bot-Desktop/build/gofbot
python ./pokecli.py
[2016-08-12T11:29:42.367Z] [electron-connect] [server] client (window_id: 1) closed.
[2016-08-12T11:29:42.916Z] [electron-connect] [server] client (window_id: 1) started.
[2016-08-12T11:29:42.945Z] [electron-connect] [server] receive message from client(window_id: 1) {"type":"initBounds","data":{"bounds":{"x":200,"y":143,"width":1280,"height":720}}}
[2016-08-12T11:29:42.948Z] [electron-connect] [server] receive message from client(window_id: 1) {"type":"getBounds"}
Python: 2016-08-12 13:29:43,254 [       cli] [INFO] PokemonGO Bot v1.0

Python: 2016-08-12 13:29:43,255 [       cli] [INFO] No config argument specified, checking for /configs/config.json

Python: 2016-08-12 13:29:43,256 [       cli] [INFO] Configuration initialized

Python: 2016-08-12 13:29:43,257 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:

Python: 2016-08-12 13:29:43,257 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics

Python: 2016-08-12 13:29:43,267 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com

Python: 2016-08-12 13:29:43,466 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTPS connection (1): adblockhost.lan.local

Python: Traceback (most recent call last):
  File "./pokecli.py", line 531, in <module>
    main()

Python:   File "./pokecli.py", line 76, in main
    health_record.login_success()
  File "/Users/jfbethlehem/Code/Git/PokemonGo-Bot-Desktop/build/gofbot/pokemongo_bot/health_record/bot_event.py", line 46, in login_success
    self.track_url('/loggedin')
  File "/Users/jfbethlehem/Code/Git/PokemonGo-Bot-Desktop/build/gofbot/pokemongo_bot/health_record/bot_event.py", line 78, in track_url
    'http://www.google-analytics.com/collect', data=data)
  File "packages/requests/api.py", line 111, in post
### Information
- OS: Mac OS (does not matter which OS though)
- Git commit: latest
- App's logs: see above.

**Comment by Outpox** [comment]
Edit your config.json (in the gofbot/configs/ folder) and set the health check option to false?
