### ISSUE TITLE
Permission denied (publickey)

### ISSUE THREAD

**Issue by sergiy-talashko** [PokemonGoF/PokemonGo-Bot-Desktop#164]
Got the error after trying update project today. Yesterday everything was fine.
I did: 

```
git pull 
npm install
```
### Expected Behavior

All modules should be installed. And sub-project should be updated.
### Actual Behavior

Got the error after calling `npm intall` :

```
[00:30:10] Finished 'build:src' after 779 ms
[00:30:10] Finished 'build:node' after 876 ms
[00:30:12] 'gofbot:update' errored after 2.17 s
[00:30:12] Error: Command failed: git submodule update --init --recursive
Cloning into 'build/gofbot'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:PokemonGoF/PokemonGo-Bot.git' into submodule path 'build/gofbot' failed

    at ChildProcess.exithandler (child_process.js:207:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
[00:30:12] 'build' errored after 2.45 s
[00:30:12] Error in plugin 'run-sequence(gofbot:update)'
Message:
    Command failed: git submodule update --init --recursive
```
### Steps to Reproduce

```
git pull
npm install
```
### Information
- OS: Ubuntu 14.04
- Git branch: Your branch is up-to-date with 'origin/development'.
- npm: 3.9.5
- node: v6.2.2

**Comment by sergiy-talashko** [comment]
I found the problem - it was missing ssh key in my github settings.
But very strange to clone project only through ssh. What if use only https?
