### ISSUE TITLE
Python Bot Error

### ISSUE THREAD

**Issue by BurntDiamondz** [PokemonGoF/PokemonGo-Bot-Desktop#166]
An error comes up titles "Error in python bot"

It has an error message like this

2016-08-13 01:31:28,992 [sentry.errors.serializer] [ERROR] maximum recursion depth exceeded while calling python object then just rambles on equations and .py file paths.

**Comment by ProjectBarks** [comment]
Run `git pull` and then `npm install` and then `npm run`

**Comment by BurntDiamondz** [comment]
what?

**Comment by BurntDiamondz** [comment]
npm not working

**Comment by BurntDiamondz** [comment]
npm run*

**Comment by BurntDiamondz** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'gulp',
1 verbose cli   'run' ]
2 info using npm@3.7.3
3 info using node@v5.8.0
4 verbose stack Error: missing script: gulp
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:147:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:57:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:345:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:309:45)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:343:3)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:113:5)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:300:12
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:414:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete](fs.js:401:12)
5 verbose cwd C:\Users\Kieran\PokemonGo-Bot-Desktop
6 error Windows_NT 6.3.9600
7 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "gulp" "run"
8 error node v5.8.0
9 error npm  v3.7.3
10 error missing script: gulp
11 error If you need help, you may report this error at:
11 error     https://github.com/npm/npm/issues
12 verbose exit [ 1, true ]
