### ISSUE TITLE
npm install fails - gulp build

### ISSUE THREAD

**Issue by slagger** [PokemonGoF/PokemonGo-Bot-Desktop#170]
_Issue without proper information won't be answered_
### Expected Behavior

Able to npm install properly
### Actual Behavior

npm install fails - failed at gulp build
### Steps to Reproduce

Execute npm install
### Information

OS - Windows 10

Error Log:

```
> PokemonGoBot@0.0.1-alpha postinstall C:\Users\Alaric\pokemongo-bot-desktop
> gulp build

C:\Users\Alaric\pokemongo-bot-desktop\gulpfile.js:45
            let parsed = data.toString().split('\n');
            ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet sup                 ported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Liftoff.handleArguments (C:\Users\Alaric\PokemonGo-Bot-Desktop\node_modul                 es\gulp\bin\gulp.js:116:3)
    at Liftoff.<anonymous> (C:\Users\Alaric\PokemonGo-Bot-Desktop\node_modules\g                 ulp\node_modules\liftoff\index.js:198:16)
    at module.exports (C:\Users\Alaric\PokemonGo-Bot-Desktop\node_modules\gulp\n                 ode_modules\liftoff\node_modules\flagged-respawn\index.js:17:3)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\                 node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE
npm ERR! PokemonGoBot@0.0.1-alpha postinstall: `gulp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the PokemonGoBot@0.0.1-alpha postinstall script 'gulp build'.
npm ERR! This is most likely a problem with the PokemonGoBot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build
```

I'm kind of a noob here, so I'm not sure what I'm doing wrong. Would be happy if someone can point me in the right direction. Thanks!

**Comment by yutelin** [comment]
see workaround in https://github.com/PokemonGoF/PokemonGo-Bot-Desktop/issues/168

**Comment by slagger** [comment]
Thanks that seemed to fix it!
