### ISSUE TITLE
Error in Python Bot

### ISSUE THREAD

**Issue by chrismou** [PokemonGoF/PokemonGo-Bot-Desktop#199]
### Expected Behavior

App should log in and do it's thang
### Actual Behavior

Bot seems to "Log in successfully" but stops there.  Few seconds of nothing, then 2 errors pop up:

![screenshot 2016-08-15 09 33 58](https://cloud.githubusercontent.com/assets/319883/17661829/77b851dc-62d9-11e6-9431-2c49e66c2f59.png)

![screenshot 2016-08-15 09 34 23](https://cloud.githubusercontent.com/assets/319883/17661973/4f6c17f8-62da-11e6-98c5-43f6efea149e.png)
### Steps to Reproduce

Download 0.2. Add required info. Run.  Have tried a few times in the past 2 hours, same error every time.  https://go.jooas.com/ showing the server as up and running.
### Information
- MacOSX
- Tried with commit 5f9617406ff94ec58e53975d98575612c6ccd953 (last checked on Friday afternoon and seemed to be working OK then).  Also tried with 0.0.2-alpha tag

Logs:

```
Python: 2016-08-15 11:16:55,506 [PokemonGoBot] [INFO] [set_start_location] Setting start location.

Python: 2016-08-15 11:16:55,507 [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.

Python: 2016-08-15 11:16:55,507 [PokemonGoBot] [INFO] [location_found] Location found: [lattitude],[longitude] ([lattitude], [longitude], 0.0)

Python: 2016-08-15 11:16:55,507 [PokemonGoBot] [INFO] [position_update] Now at ([lattitude], [longitude], 0)

Python: 2016-08-15 11:16:55,508 [PokemonGoBot] [INFO] [login_started] Login procedure started.

Python: 2016-08-15 11:16:57,670 [PokemonGoBot] [INFO] [login_successful] Login successful.

Python: 2016-08-15 11:17:03,267 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 4/15

Python: 2016-08-15 11:17:04,241 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 5/15

Python: 2016-08-15 11:17:05,838 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 6/15

Python: 2016-08-15 11:17:06,814 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 7/15

Python: 2016-08-15 11:17:07,833 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 8/15

Python: 2016-08-15 11:17:08,891 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 9/15

Python: 2016-08-15 11:17:10,238 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 10/15

Python: 2016-08-15 11:17:11,420 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 11/15

Python: 2016-08-15 11:17:12,689 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 12/15

Python: 2016-08-15 11:17:13,717 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 13/15

Python: 2016-08-15 11:17:14,672 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 14/15

Python: 2016-08-15 11:17:15,922 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 15/15

Python: Traceback (most recent call last):
  File "./pokecli.py", line 522, in <module>

Python:     main()
  File "./pokecli.py", line 138, in main
    report_summary(bot)
  File "./pokecli.py", line 147, in report_summary
    metrics.capture_stats()
  File "/Users/mou/Dev/PokemonGo-Bot-Desktop/gofbot/pokemongo_bot/metrics.py", line 76, in capture_stats
    response_dict = request.call()
  File "/Users/mou/Dev/PokemonGo-Bot-Desktop/gofbot/pokemongo_bot/api_wrapper.py", line 133, in call
    raise ServerBusyOrOfflineException()

Python: pgoapi.exceptions.ServerBusyOrOfflineException

Python: 2016-08-15 11:17:15,932 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/usr/local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/usr/local/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/usr/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
```

Note, I've blanked out the lat/lng. If you need it for debugging, feel free to email me for the details.

**Comment by tnsbm** [comment]
Go to your config.json and set health_check to false

**Comment by tmathura** [comment]
I also have this problem. There is no 'health_check' but there is a 'health_record', I set it to false, it logs in now and then logs off after a few seconds, then I am back at the login screen.

**Comment by Fatalicious** [comment]
@tmathura same

**Comment by Fatalicious** [comment]
Have you tried to login on the pokemon go app ? I have this error on a banned account, maybe you're b&.

**Comment by tpai** [comment]
These message will show when account is banned.

**Comment by andrenagusch** [comment]
Jup :) Experiment "bot" _failed_! Bot account banned level 26.
- [x] 2 times soft banned
- [x] Always used bot near by my own location
- [x] max. 4h a day
- [x] walk "5", "25" and "30"
- [x] Name template
- [x] evolve time 20

**Comment by Tomygames** [comment]
andrenagusch, i have a working bypass, but i won't tell it as it will be patched too quickly , modified this bot, just "Experiment" again and you will find it :p

**Comment by Tomygames** [comment]
For example, i was never soft banned with my version and had 15 walk speed + i tp to pokemons

**Comment by tmathura** [comment]
I was not banned. I can log onto it on the phone. It's actually a new account, fresh!

**Comment by chrismou** [comment]
Just tried creating a new account to test. Got the same error first time logging in.  Tried setting `health_record` to false, but had the same issue as @tmathura - threw me back to the login screen within a few seconds.

**Comment by RoyLeeKB** [comment]
Facing the exact same issue right now.

Was using this bot and it worked fine for the past 3 days.
Logged in an hour ago and it worked until I came with the above error.

Problem could be with the Bot or API and unlikely to be with the config file as it was running fine previously,

I tried troubleshooting by doing a clean install but still encounter the exact same issue.

Please advise! Thanks :)

*PS, Account is not banned. Still playable in phone.

EDIT: After 4 hours of waiting, Bot is now up and running with the exact same files,
No changes in config file.

EDIT 2: Bot is down again with the same ascii bug. Waited for 5 hours but still no avail.
