### ISSUE TITLE
Error when starting program

### ISSUE THREAD

**Issue by JVenberg** [PokemonGoF/PokemonGo-Bot-Desktop#2]
### **Error:**

**A JavaScript error occurred in the main process**
Uncaught Exception:
Error: spawn python ENOENT
    at exports._errnoException (util.js:949:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
### **Operating System:**

OSX El Capitan

**Comment by tzull** [comment]
![image](https://cloud.githubusercontent.com/assets/20562271/17142973/22237eca-537c-11e6-8e1b-4603238db33f.png)
Same error when starting.

OS : Windows 7

**Comment by pyr0ball** [comment]
Same error, windows 10 x64, latest commit 5f96174.

screenshot shows fixes applied to this issue in past are present
![image](https://cloud.githubusercontent.com/assets/8482805/17575630/bc23ea24-5f1f-11e6-8824-52b5ef8c15ce.png)
