### ISSUE TITLE
Constant Error in Python Bot

### ISSUE THREAD

**Issue by jessekjz** [PokemonGoF/PokemonGo-Bot-Desktop#232]
Hi Guys, first post, I hope its okay.

Expected Behavior:
Bot should work as normal

Actual Behavior:
Ever since yesterday the app errors out on the loading status for the bot.
Downloaded the app again, same issue.

Steps to Reproduce
No clue, I can't find out what went wrong.

Information
Mac OSX 10.11.4

Error Message:
2016-08-23 16:08:44,746 [sentry.errors.uncaught] [ERROR] [u'ServerBusyOrOfflineException', u'  File "pokecli.py", line 504, in <module>', u'  File "pokecli.py", line 132, in main', u'  File "pokecli.py", line 141, in report_summary', u'  File "pokemongo_bot/metrics.py", line 76, in capture_stats', u'  File "pokemongo_bot/api_wrapper.py", line 133, in call']

2016-08-23 16:08:44,742 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 891, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)

**Comment by ghost** [comment]
Same issue for me, except I am a Windows user. The error message prompt on Windows is a bit different in the sense that I can not highlight and copy the error message.

Operating System: Windows 10 64-bit

![error](https://cloud.githubusercontent.com/assets/6528430/17912472/6aec3938-6959-11e6-992c-41da9061b597.png)

**Comment by roshcamlian** [comment]
I know nothing about these but it seemed it occurs naturally every now and then. Go re-run the app and see if it still pops up, just keep trying and eventually it'd be back to how it was.

**Comment by KyonCN** [comment]
Same issue for me like Sp333th and the prompt is same.
I can not log in, because the program breaks down when i just run it.

**Comment by roshcamlian** [comment]
@KyonCN you might be pertaining to just an error within the config. You might have configured something the app couldn't launch. Somethin like that. Have you tried launching the app without changing anything but the login information that you need with the default config?

**Comment by Outpox** [comment]
Duplicate #225
