### ISSUE TITLE
File "./pokecli.py", line 38, in <module>     import requests

### ISSUE THREAD

**Issue by mes113** [PokemonGoF/PokemonGo-Bot-Desktop#24]
Trying to run bot , but i get error . 

Starting Python process...
Got open port: 8000
Bot path: /Applications/MAMP/htdocs/PokemonGo-Bot-Desktop/gofbot
python ./pokecli.py
Bot path: /Applications/MAMP/htdocs/PokemonGo-Bot-Desktop/gofbot/web
python serveit.py 8000
Python: Traceback (most recent call last):
  File "./pokecli.py", line 38, in <module>
    import requests
ImportError: No module named requests

I'm using mac os x el capitan .

Already trying to do 

pip uninstall requests
pip install requests

**Comment by lightningfuzion2** [comment]
you probably have two pythons installed on your computer. just change code in main.js:

pythonCmd = path.join(__dirname, 'pywin', 'python.exe');
change to
pythonCmd = path.join('C:/', 'Python27', 'python.exe');

should get it running

**Comment by ghost** [comment]
Thank @lightningfuzion2!

**Comment by AngeloGiurano** [comment]
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-MXBj4j/protobuf-to-dict/setup.py", line 25, in <module>
        'Topic :: Software Development :: Libraries :: Python Modules',
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 239, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 263, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 580, in resolve
        raise VersionConflict(dist,req) # XXX put more info here
    pkg_resources.VersionConflict: (six 1.4.1 (/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python), Requirement.parse('six>=1.9'))

when running pip install -r requirements.txt

**Comment by pokemontrainer718** [comment]
where do i get that @lightningfuzion2 or in other words where is main.js

**Comment by dschoon** [comment]
@pokemontrainer718 looks like it's in: `src/app.js`
