### ISSUE TITLE
Problems with encrypt.dll (have read issue #138)

### ISSUE THREAD

**Issue by Zakli** [PokemonGoF/PokemonGo-Bot-Desktop#249]
I've downloaded both the 32bit and 64bit encrypt.dll and tried with both. If I choose their location with the app I get a message saying: 

**2016-08-30 18:41:18,976 [PokemonGoBot] [ERROR] encrypt.dll is not found! Please place it in the bots root directory or set libencrypt_location in config.**

This happens with both versions.

When I rename them to encrypt.dll and place them in resorces/app/gofbot i get this error message:

```
[Window Title]
Whoops

[Main Instruction]
Error in python bot

[Content]
2016-08-30 18:42:23,513 [sentry.errors.serializer] [ERROR] maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "packages\raven\utils\serializer\manager.py", line 76, in transform
    return repr(value)
  File "C:\Users\Slynan\Downloads\PikaBot-0.2-alpha-win\resources\app\pywin\lib\ctypes\__init__.py", line 369, in __repr__
    (self._handle & (_sys.maxint*2 + 1)),
  File "C:\Users\Slynan\Downloads\PikaBot-0.2-alpha-win\resources\app\pywin\lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "C:\Users\Slynan\Downloads\PikaBot-0.2-alpha-win\resources\app\pywin\lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "C:\Users\Slynan\Downloads\PikaBot-0.2-alpha-win\resources\app\pywin\lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "C:\Users\Slynan\Downloads\PikaBot-0.2-alpha-win\resources\app\pywin\lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "C:\Users\Slynan\Downloads\PikaBot-0.2-alpha-win\resources\app\pywin\lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "C:\Users\Slynan\Downloads\PikaBot-0.2-alpha-win\resources\app\pywin\lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "C:\Users\Slynan\Downloads\PikaBot-0.2-alpha-win\resources\app\pywin\lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "C:\Users\Slynan\Downloads\PikaBot-0.2-alpha-win\resources\app\pywin\lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "C:\Users\Slynan\Downloads\PikaBot-0.2-alpha-win\resources\app\pywin\lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "C:\Users\Slynan\Downloads\PikaBot-0.2-alpha-win\resources\app\pywin\lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "C:\Users\Slynan\Downloads\PikaBot-0.2-alpha-win\resources\app\pywin\lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "C:\Users\Slynan\Downloads\PikaBot-0.2-alpha-win\resources\app\pywin\lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "C:\Users\Slynan\Downloads\PikaBot-0.2-alpha-win\resources\app\pywin\lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "C:\Users\Slynan\Downloads\PikaBot-0.2-alpha-win\resources\app\pywin\lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "C:\Users\Slynan\Downloads\PikaBot-0.2-alpha-win\resources\app\pywin\lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "C:\Users\Slynan\Downloads\PikaBot-0.2-alpha-win\resources\app\pywin\lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "C:\Users\Slynan\Downloads\PikaBot-0.2-alpha-win\resources\app\pywin\lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "C:\Users\Slynan\Downloads\PikaBot-0.2-alpha-win\resources\app\pywin\lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "C:\Users\Slynan\Downloads\PikaBot-0.2-alpha-win\resources\app\pywin\lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "C:\Users\Slynan\Downloads\PikaBot-0.2-alpha-win\resources\app\pywin\lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "C:\Users\Slynan\Downloads\PikaBot-0.2-alpha-win\resources\app\pywin\lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "C:\Users\Slynan\Dow[Window Title]
Whoops

[Main Instruction]
Error in python bot

[Content]
e 375, in __getattr__
    func = self.__getitem__(name)
  File "C:\Users\Slynan\Downloads\PikaBot-0.2-alpha-win\resources\app\pywin\lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "C:\Users\Slynan\Downloads\PikaBot-0.2-alpha-win\resources\app\pywin\lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "C:\Users\Slynan\Downloads\PikaBot-0.2-alpha-win\resources\app\pywin\lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "C:\Users\Slynan\Downloads\PikaBot-0.2-alpha-win\resources\app\pywin\lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "C:\Users\Slynan\Downloads\PikaBot-0.2-alpha-win\resources\app\pywin\lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "C:\Users\Slynan\Downloads\PikaBot-0.2-alpha-win\resources\app\pywin\lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "C:\Users\Slynan\Downloads\PikaBot-0.2-alpha-win\resources\app\pywin\lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "C:\Users\Slynan\Downloads\PikaBot-0.2-alpha-win\resources\app\pywin\lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "C:\Users\Slynan\Downloads\PikaBot-0.2-alpha-win\resources\app\pywin\lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "C:\Users\Slynan\Downloads\PikaBot-0.2-alpha-win\resources\app\pywin\lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "C:\Users\Slynan\Downloads\PikaBot-0.2-alpha-win\resources\app\pywin\lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "C:\Users\Slynan\Downloads\PikaBot-0.2-alpha-win\resources\app\pywin\lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "C:\Users\Slynan\Downloads\PikaBot-0.2-alpha-win\resources\app\pywin\lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "C:\Users\Slynan\Downloads\PikaBot-0.2-alpha-win\resources\app\pywin\lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "C:\Users\Slynan\Downloads\PikaBot-0.2-alpha-win\resources\app\pywin\lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "C:\Users\Slynan\Downloads\PikaBot-0.2-alpha-win\resources\app\pywin\lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "C:\Users\Slynan\Downloads\PikaBot-0.2-alpha-win\resources\app\pywin\lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "C:\Users\Slynan\Downloads\PikaBot-0.2-alpha-win\resources\app\pywin\lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "C:\Users\Slynan\Downloads\PikaBot-0.2-alpha-win\resources\app\pywin\lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "C:\Users\Slynan\Downloads\PikaBot-0.2-alpha-win\resources\app\pywin\lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "C:\Users\Slynan\Downloads\PikaBot-0.2-alpha-win\resources\app\pywin\lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "C:\Users\Slynan\Downloads\PikaBot-0.2-alpha-win\resources\app\pywin\lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "C:\Users\Slynan\Downloads\PikaBot-0.2-alpha-win\resources\app\pywin\lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "C:\Users\Slynan\Downloads\PikaB
```

I'm on 64bit win10

**Comment by LUCKASSs** [comment]
I used the 32bits and rename it into encrypt.dll and that worked for me on W10 x64.

I used this one if you want to test : https://dl.dropboxusercontent.com/u/167503541/encrypt.dll

(But I don't know why, when the bot work the map doesn't load on the screen)

**Comment by boscorelly** [comment]
I had the same problem : when you select file, it's never saved.
And when you put the 64bits in resources\app\gofbot it doesn't work.
But ! If you place the 32 bits, it's ok.
