### ISSUE TITLE
Transferring items?

### ISSUE THREAD

**Issue by ishaanbabani** [PokemonGoF/PokemonGo-Bot-Desktop#252]
I know in the config that there is a way to transfer items when you have too many, but when I saw this the items available were Pokeballs, Revives, Potions, Super Potions, Hyper potions, and Razz Berries. When I got great balls I ended up amassing 170 of them because it wasn't in the config. Could I have some help with this?

**Comment by KDA809** [comment]
```
    {
        "type": "RecycleItems",
        "config": {
            "item_filter": {
                "Pokeball": {
                    "keep": 10
                },
                "Potion": {
                    "keep": 10
                },
                "Super Potion": {
                    "keep": 30
                },
                "Hyper Potion": {
                    "keep": 0
                },
                "Revive": {
                    "keep": 0
                },
                "Razz Berry": {
                    "keep": 5
                }
            }
        }
    },
```

**Comment by KDA809** [comment]
@doggo42 code above replace in your config.json file 😜🤓🤓

**Comment by ishaanbabani** [comment]
Thanks for that, but how do I set it to transfer great balls as well? @iiCe89

**Comment by KDA809** [comment]
@doggo42 (pokeballs) sets them all i believe as ive never had my items full ever when using this bot

**Comment by MrAppleMania** [comment]
If you want, you can use mine. Just replace the numbers with yours.

(All numbers added together should be about 200-240, because I guess you want to have some space over for your Incubators, Lucky Eggs and Incenses!)

```
    {
        "type": "RecycleItems",
        "config": {
            "item_filter": {
                "Pokeball": {
                    "keep": 0
                },
                "Greatball": {
                    "keep": 0
                },
                "Ultraball": {
                    "keep": 100
                },
                "Potion": {
                    "keep": 0
                },
                "Super Potion": {
                    "keep": 0
                },
                "Hyper Potion": {
                    "keep": 0
                },
                "Max Potion": {
                    "keep": 50
                },
                "Revive": {
                    "keep": 0
                },
                "Razz Berry": {
                    "keep": 50
                }
            }
        }
    },
```

**Comment by ishaanbabani** [comment]
Uncaught Exception:SyntaxError: Unexpected token “ in JSON at position 1143    at Object.parse (native)    at startPython (/Users/ishaanbabani/Documents/PoGo bot/PikaBot.app/Contents/Resources/app/main.js:198:23)    at EventEmitter.<anonymous> (/Users/ishaanbabani/Documents/PoGo bot/PikaBot.app/Contents/Resources/app/main.js:118:5)    at emitMany (events.js:127:13)    at EventEmitter.emit (events.js:201:7)    at WebContents.<anonymous> (/Users/ishaanbabani/Documents/PoGo bot/PikaBot.app/Contents/Resources/electron.asar/browser/api/web-contents.js:209:13)    at emitTwo (events.js:106:13)    at WebContents.emit (events.js:191:7)

...could you attach your config.json file please?
@MrAppleMania
