### ISSUE TITLE
Config Edit Issues

### ISSUE THREAD

**Issue by jameswhote** [PokemonGoF/PokemonGo-Bot-Desktop#267]
I want to set up my bot to release everything except my top 200 cp pokemon. I know the command lines and everything but it always comes up with an error for an unexpected line.
if you could please give me a way of inserting this it would really help.

**Comment by jameswhote** [comment]
Uncaught Exception:
SyntaxError: Unexpected string in JSON at position 3012
    at Object.parse (native)
    at startPython (/Users/student/Desktop/PikaBot.app/Contents/Resources/app/main.js:198:23)
    at EventEmitter.<anonymous> (/Users/student/Desktop/PikaBot.app/Contents/Resources/app/main.js:118:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/Users/student/Desktop/PikaBot.app/Contents/Resources/electron.asar/browser/api/web-contents.js:209:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)

**Comment by Outpox** [comment]
Please validate your code with [JSONLint](http://jsonlint.com/). From the logs it seems to be an issue with it.
