### ISSUE TITLE
PikaBot will not login

### ISSUE THREAD

**Issue by JMeisterDesign** [PokemonGoF/PokemonGo-Bot-Desktop#273]
_Issue without proper information won't be answered_
### Expected Behavior

Expect the app to login to my google account.
### Actual Behavior

The app throws a JavaScript exception
### Steps to Reproduce

Clicking Login to Google throws this error...

Uncaught Exception:
Error: EROFS: read-only file system, rename '/private/var/folders/b8/wp4k_xkn45g48w7hg6z50pzw0000gn/T/AppTranslocation/B6537F93-B151-43D7-93E3-E7FBC5235833/d/PikaBot.app/Contents/Resources/app/gofbot/configs/config.json.example' -> '/private/var/folders/b8/wp4k_xkn45g48w7hg6z50pzw0000gn/T/AppTranslocation/B6537F93-B151-43D7-93E3-E7FBC5235833/d/PikaBot.app/Contents/Resources/app/gofbot/configs/config.json'
    at Error (native)
    at Object.fs.renameSync (fs.js:809:18)
    at startPython (/private/var/folders/b8/wp4k_xkn45g48w7hg6z50pzw0000gn/T/AppTranslocation/B6537F93-B151-43D7-93E3-E7FBC5235833/d/PikaBot.app/Contents/Resources/app/main.js:184:8)
    at EventEmitter.<anonymous> (/private/var/folders/b8/wp4k_xkn45g48w7hg6z50pzw0000gn/T/AppTranslocation/B6537F93-B151-43D7-93E3-E7FBC5235833/d/PikaBot.app/Contents/Resources/app/main.js:118:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/private/var/folders/b8/wp4k_xkn45g48w7hg6z50pzw0000gn/T/AppTranslocation/B6537F93-B151-43D7-93E3-E7FBC5235833/d/PikaBot.app/Contents/Resources/electron.asar/browser/api/web-contents.js:209:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
### Information
- OS - Mac OS 10.12 Sierra
- Git commit ( to get git commit run `git log -1 --format="%H"`)
- App's logs

**Comment by KDA809** [comment]
do you have 2 step auth on your gmail account if so remove & try to log in again

**Comment by JMeisterDesign** [comment]
I do not have 2 step auth on this particular gmail account

**Comment by KDA809** [comment]
have you altered anything in files ?

**Comment by JMeisterDesign** [comment]
No, I downloaded it, entered my credentials and when I hit login, thats what I get.

**Comment by azrinabil1317-bit** [comment]
.allmenu
