### ISSUE TITLE
Error when starting

### ISSUE THREAD

**Issue by MarkPaspirgilis** [PokemonGoF/PokemonGo-Bot-Desktop#278]
*Issue without proper information won't be answered*
### Information
 - Windows
 - Latest
 - [Window Title]
Whoops

[Main Instruction]
Error in python bot

[Content]
2017-01-24 01:01:32,940 [sentry.errors.serializer] [ERROR] maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "packages\raven\utils\serializer\manager.py", line 76, in transform
    return repr(value)
  File "C:\Bots\PikaBot\resources\app\pywin\lib\ctypes\__init__.py", line 369, in __repr__
    (self._handle & (_sys.maxint*2 + 1)),
  File "C:\Bots\PikaBot\resources\app\pywin\lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "C:\Bots\PikaBot\resources\app\pywin\lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "C:\Bots\PikaBot\resources\app\pywin\lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "C:\Bots\PikaBot\resources\app\pywin\lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "C:\Bots\PikaBot\resources\app\pywin\lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "C:\Bots\PikaBot\resources\app\pywin\lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "C:\Bots\PikaBot\resources\app\pywin\lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "C:\Bots\PikaBot\resources\app\pywin\lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "C:\Bots\PikaBot\resources\app\pywin\lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "C:\Bots\PikaBot\resources\app\pywin\lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "C:\Bots\PikaBot\resources\app\pywin\lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "C:\Bots\PikaBot\resources\app\pywin\lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "C:\Bots\PikaBot\resources\app\pywin\lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "C:\Bots\PikaBot\resources\app\pywin\lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "C:\Bots\PikaBot\resources\app\pywin\lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "C:\Bots\PikaBot\resources\app\pywin\lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "C:\Bots\PikaBot\resources\app\pywin\lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "C:\Bots\PikaBot\resources\app\pywin\lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "C:\Bots\PikaBot\resources\app\pywin\lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "C:\Bots\PikaBot\resources\app\pywin\lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "C:\Bots\PikaBot\resources\app\pywin\lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "C:\Bots\PikaBot\resources\app\pywin\lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "C:\Bots\PikaBot\resources\app\pywin\lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "C:\Bots\PikaBot\resources\app\pywin\lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "C:\Bots\PikaBot\resources\app\pywin\lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "C:\Bots\PikaBot\resources\app\pywin\lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "C:\Bots\PikaBot\resources

**Comment by ghost** [comment]
Got the same problem
