### ISSUE TITLE
Linux version?

### ISSUE THREAD

**Issue by ViBE-HU** [PokemonGoF/PokemonGo-Bot-Desktop#31]
Is it already available for Linux? Or it will be if you can fix the existing issues?

**Comment by JVenberg** [comment]
What is your current issue so I can try to fix it?

**Comment by ViBE-HU** [comment]
@JVenberg You mean it's already available?

**Comment by g2384** [comment]
@ViBE-HU I just installed it on Ubuntu 16.04 without any issue. It can run properly.

**Comment by ViBE-HU** [comment]
Hm, first when I red the instructions I thought `brew` is an OSX only tools so I did not try to install it. Btw there is no clear information about installation and workarounds. I thought Linux is not supported. Now I tried to install and I get some red text while install. But it finished and here is the output when try to run it:

```
> electron main.js

sh: 1: electron: not found

npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! PokemonGoBot@0.0.1-alpha start: `electron main.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the PokemonGoBot@0.0.1-alpha start script 'electron main.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the PokemonGoBot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs PokemonGoBot
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls PokemonGoBot
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/userPokemonGo-Bot-Desktop/npm-debug.log
```

and here is the log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle PokemonGoBot@0.0.1-alpha~prestart: PokemonGoBot@0.0.1-alpha
6 silly lifecycle PokemonGoBot@0.0.1-alpha~prestart: no script for prestart, continuing
7 info lifecycle PokemonGoBot@0.0.1-alpha~start: PokemonGoBot@0.0.1-alpha
8 verbose lifecycle PokemonGoBot@0.0.1-alpha~start: unsafe-perm in lifecycle true
9 verbose lifecycle PokemonGoBot@0.0.1-alpha~start: PATH: /usr/share/npm/bin/node-gyp-bin:/home/user/PokemonGo-Bot-Desktop/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin
10 verbose lifecycle PokemonGoBot@0.0.1-alpha~start: CWD: /home/user/PokemonGo-Bot-Desktop
11 silly lifecycle PokemonGoBot@0.0.1-alpha~start: Args: [ '-c', 'electron main.js' ]
12 info lifecycle PokemonGoBot@0.0.1-alpha~start: Failed to exec start script
13 verbose stack Error: PokemonGoBot@0.0.1-alpha start: `electron main.js`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
13 verbose stack     at emitTwo (events.js:87:13)
13 verbose stack     at ChildProcess.emit (events.js:172:7)
13 verbose stack     at maybeClose (internal/child_process.js:821:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid PokemonGoBot@0.0.1-alpha
15 verbose cwd /home/user/PokemonGo-Bot-Desktop
16 error Linux 4.4.0-31-generic
17 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
18 error node v4.2.6
19 error npm  v3.5.2
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error PokemonGoBot@0.0.1-alpha start: `electron main.js`
24 error spawn ENOENT
25 error Failed at the PokemonGoBot@0.0.1-alpha start script 'electron main.js'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the PokemonGoBot package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     electron main.js
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs PokemonGoBot
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls PokemonGoBot
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]
```

**Comment by g2384** [comment]
It seems you need to install this module first [https://github.com/electron/electron](https://github.com/electron/electron)

**Comment by ViBE-HU** [comment]
Now I get this:

```
sudo npm install electron-prebuilt -g
loadDep:wrappy → network  ▀ ╢██████████████████████████████░░░░░░░░░░░░░░░░░░░░░/usr/local/bin/electron -> /usr/local/lib/node_modules/electron-prebuilt/cli.js

> electron-prebuilt@1.3.1 postinstall /usr/local/lib/node_modules/electron-prebuilt
> node install.js

sh: 1: node: not found
npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "electron-prebuilt" "-g"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! electron-prebuilt@1.3.1 postinstall: `node install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the electron-prebuilt@1.3.1 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/PokemonGo-Bot-Desktop/npm-debug.log
```

**Comment by g2384** [comment]
Ok, did you successfully do `brew install python node`? The nodejs is missing. 

Try

```
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs
```

(It may cause further issues, I should really save my terminal commands. I don't remember which tutorial I was using. Try to google `linux install nodejs v6`.)
