### ISSUE TITLE
this bot is not suitable for windows,right?Because brew doesn't work in windows

### ISSUE THREAD

**Issue by yyz20002008** [PokemonGoF/PokemonGo-Bot-Desktop#34]

**Comment by JVenberg** [comment]
It will work as long as you install node some other way. Try this link: https://nodejs.org/en/download/

**Comment by vergilet** [comment]
Few things:
I installed everything on ubuntu anf on both of my win PCs.
Ubuntu works cool. On both of windowses it starts, but logging the error message inside the pikabot dev console.

**Comment by vergilet** [comment]
Like here #16

**Comment by darouwan** [comment]
@vergilet how did you install it on Ubuntu? I got the following error when running "npm install"
`

> electron-prebuilt@1.3.1 postinstall /home/darouwan/PokemonGo-Bot-Desktop/node_modules/electron-prebuilt
> node install.js

Downloading electron-v1.3.1-linux-x64.zip
Error: socket hang up
/home/darouwan/PokemonGo-Bot-Desktop/node_modules/electron-prebuilt/install.js:22
  throw err
  ^

Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1048:19)
    at TLSSocket.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at TLSSocket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)
npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! electron-prebuilt@1.3.1 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-prebuilt@1.3.1 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/darouwan/PokemonGo-Bot-Desktop/npm-debug.log
`

**Comment by vergilet** [comment]
@darouwan ubuntu 16.04 without excesses, just `npm install`.
I had the same problem with electron on windows, so I just have cleaned up everything in npm and started again from the beginning. Second change was succesfull for electron instalation.
