### ISSUE TITLE
Install error OSX

### ISSUE THREAD

**Issue by blackmambacode** [PokemonGoF/PokemonGo-Bot-Desktop#44]
I'm getting this on the latest OS X:

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/6.3.1/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! PokemonGoBot@0.0.1-alpha postinstall: `cd ./gofbot/ && pip install -r requirements.txt`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the PokemonGoBot@0.0.1-alpha postinstall script 'cd ./gofbot/ && pip install -r requirements.txt'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the PokemonGoBot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd ./gofbot/ && pip install -r requirements.txt
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs PokemonGoBot
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls PokemonGoBot
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/XXXXXX/Desktop/PokemonGo-Bot-Desktop/npm-debug.log

**Comment by JVenberg** [comment]
Can you try pip install -r requirements.txt on the gofbot directory and tell me if it works?

**Comment by innrwrld** [comment]
Same issue installed.  Attempted to run the pip installation from within the gofbot/ directory & still got the following:

```
Collecting protobuf-to-dict==0.1.0 (from -r requirements.txt (line 7))
  Using cached protobuf-to-dict-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:

    Installed /private/var/folders/d7/313wrk9d5kq0xxk842lzx39m0000gn/T/pip-build-Z5S1tJ/protobuf-to-dict/.eggs/nosexcover-1.0.10-py2.7.egg
    Searching for coverage
    Reading https://pypi.python.org/simple/coverage/
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/d7/313wrk9d5kq0xxk842lzx39m0000gn/T/pip-build-Z5S1tJ/protobuf-to-dict/setup.py", line 25, in <module>
        'Topic :: Software Development :: Libraries :: Python Modules',
      File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 269, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 826, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1092, in best_match
        return self.obtain(req, installer)
      File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1104, in obtain
        return installer(requirement)
      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 380, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 652, in easy_install
        not self.always_copy, self.local_index
      File "/usr/local/lib/python2.7/site-packages/setuptools/package_index.py", line 607, in fetch_distribution
        self.find_packages(requirement)
      File "/usr/local/lib/python2.7/site-packages/setuptools/package_index.py", line 444, in find_packages
        self.scan_url(self.index_url + requirement.unsafe_name+'/')
      File "/usr/local/lib/python2.7/site-packages/setuptools/package_index.py", line 778, in scan_url
        self.process_url(url, True)
      File "/usr/local/lib/python2.7/site-packages/setuptools/package_index.py", line 319, in process_url
        page = f.read()
      File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 355, in read
        data = self._sock.recv(rbufsize)
      File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 612, in read
        s = self.fp.read(amt)
      File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 384, in read
        data = self._sock.recv(left)
      File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 756, in recv
        return self.read(buflen)
      File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 643, in read
        v = self._sslobj.read(len)
    socket.error: [Errno 54] Connection reset by peer

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/d7/313wrk9d5kq0xxk842lzx39m0000gn/T/pip-build-Z5S1tJ/protobuf-to-dict/
```

**Comment by blackmambacode** [comment]
@JVenberg Does not work either. 

it does work with this:
$ virtualenv .  
$ source bin/activate  
$ pip install -r requirements.txt

**Comment by innrwrld** [comment]
I got it to install in virtualenv with no issue, but did then get the following on init, but may be remedied with a manual init (haven't tried yet):

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/6.3.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start' ]
2 info using npm@3.10.3
3 info using node@v6.3.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle PokemonGoBot@0.0.1-alpha~prestart: PokemonGoBot@0.0.1-alpha
6 silly lifecycle PokemonGoBot@0.0.1-alpha~prestart: no script for prestart, continuing
7 info lifecycle PokemonGoBot@0.0.1-alpha~start: PokemonGoBot@0.0.1-alpha
8 verbose lifecycle PokemonGoBot@0.0.1-alpha~start: unsafe-perm in lifecycle true
9 verbose lifecycle PokemonGoBot@0.0.1-alpha~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/dkennedy/PokemonGo-Bot-Desktop/node_modules/.bin:/usr/local/Cellar/node/6.3.1/bin:/Users/dkennedy/PokemonGo-Bot-Desktop/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin
10 verbose lifecycle PokemonGoBot@0.0.1-alpha~start: CWD: /Users/dkennedy/PokemonGo-Bot-Desktop
11 silly lifecycle PokemonGoBot@0.0.1-alpha~start: Args: [ '-c', 'electron main.js' ]
12 silly lifecycle PokemonGoBot@0.0.1-alpha~start: Returned: code: 1  signal: null
13 info lifecycle PokemonGoBot@0.0.1-alpha~start: Failed to exec start script
14 verbose stack Error: PokemonGoBot@0.0.1-alpha start: `electron main.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid PokemonGoBot@0.0.1-alpha
16 verbose cwd /Users/dkennedy/PokemonGo-Bot-Desktop
17 error Darwin 16.0.0
18 error argv "/usr/local/Cellar/node/6.3.1/bin/node" "/usr/local/bin/npm" "start"
19 error node v6.3.1
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error PokemonGoBot@0.0.1-alpha start: `electron main.js`
22 error Exit status 1
23 error Failed at the PokemonGoBot@0.0.1-alpha start script 'electron main.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the PokemonGoBot package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     electron main.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs PokemonGoBot
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls PokemonGoBot
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
