### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 

### ISSUE THREAD

**Issue by checkplys** [PokemonGoF/PokemonGo-Bot-Desktop#46]
When running "npm install" I get `Command "python setup.py egg_info" failed with error code 1 in C:\Users\ricar\AppData\Local\Temp\pip-build-4k78o_h6\universal-analytics-python\`

**Comment by JVenberg** [comment]
Can you give more console output context to this?

**Comment by checkplys** [comment]
`C:\Users\ricar\Desktop\bott\PokemonGo-Bot-Desktop>npm install

> PokemonGoBot@0.0.1-alpha postinstall C:\Users\ricar\Desktop\bott\PokemonGo-Bot-Desktop
> cd ./gofbot/ && pip install -r requirements.txt

Obtaining pgoapi from git+https://github.com/tejado/pgoapi.git@81e786cabf027a1c8fbd1e9a07e1c11aa3d8ee8b#egg=pgoapi (from -r requirements.txt (line 1))
  Skipping because already up-to-date.
Collecting geopy==1.11.0 (from -r requirements.txt (line 2))
  Using cached geopy-1.11.0-py2.py3-none-any.whl
Collecting protobuf==3.0.0b4 (from -r requirements.txt (line 3))
  Using cached protobuf-3.0.0b4-py2.py3-none-any.whl
Collecting requests==2.10.0 (from -r requirements.txt (line 4))
  Using cached requests-2.10.0-py2.py3-none-any.whl
Collecting s2sphere==0.2.4 (from -r requirements.txt (line 5))
  Using cached s2sphere-0.2.4-py2.py3-none-any.whl
Collecting gpsoauth==0.3.0 (from -r requirements.txt (line 6))
  Using cached gpsoauth-0.3.0.tar.gz
Collecting protobuf-to-dict==0.1.0 (from -r requirements.txt (line 7))
  Using cached protobuf-to-dict-0.1.0.tar.gz
Collecting googlemaps==2.4.4 (from -r requirements.txt (line 8))
  Using cached googlemaps-2.4.4.tar.gz
Collecting colorama==0.3.7 (from -r requirements.txt (line 9))
  Using cached colorama-0.3.7-py2.py3-none-any.whl
Collecting enum34==1.1.6 (from -r requirements.txt (line 10))
  Using cached enum34-1.1.6-py3-none-any.whl
Collecting pyyaml==3.11 (from -r requirements.txt (line 11))
  Using cached PyYAML-3.11.zip
Collecting haversine==0.4.5 (from -r requirements.txt (line 12))
  Using cached haversine-0.4.5.tar.gz
Collecting polyline==1.3.1 (from -r requirements.txt (line 13))
  Using cached polyline-1.3.1-py2.py3-none-any.whl
Collecting python-socketio==1.4.2 (from -r requirements.txt (line 14))
  Using cached python-socketio-1.4.2.tar.gz
Collecting flask==0.11.1 (from -r requirements.txt (line 15))
  Using cached Flask-0.11.1-py2.py3-none-any.whl
Collecting socketIO_client==0.7.0 (from -r requirements.txt (line 16))
  Using cached socketIO-client-0.7.0.tar.gz
Collecting eventlet==0.19.0 (from -r requirements.txt (line 17))
  Using cached eventlet-0.19.0-py2.py3-none-any.whl
Collecting universal-analytics-python==0.2.4 (from -r requirements.txt (line 18))
  Using cached universal-analytics-python-0.2.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ricar\AppData\Local\Temp\pip-build-78s2n4pu\universal-analytics-python\setup.py", line 5, in <module>
        print >>sys.stderr, "Preparing version {0}\n".format(VERSION or "NOTFOUND")
    TypeError: unsupported operand type(s) for >>: 'builtin_function_or_method' and '_io.TextIOWrapper'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\ricar\AppData\Local\Temp\pip-build-78s2n4pu\universal-analytics-python\

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! PokemonGoBot@0.0.1-alpha postinstall: `cd ./gofbot/ && pip install -r requirements.txt`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the PokemonGoBot@0.0.1-alpha postinstall script 'cd ./gofbot/ && pip install -r requirements.txt'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the PokemonGoBot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd ./gofbot/ && pip install -r requirements.txt
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs PokemonGoBot
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls PokemonGoBot
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ricar\Desktop\bott\PokemonGo-Bot-Desktop\npm-debug.log

C:\Users\ricar\Desktop\bott\PokemonGo-Bot-Desktop>`

**Comment by noxonnor** [comment]
I am guessing this is because you're running Python 3 instead of 2.

**Comment by checkplys** [comment]
@noxonnor Going to try using Python 2

@JVenberg With the new PokemonGO update a lot of third party apps are not working, does this bot still work?

**Comment by sniok** [comment]
@checkplys Yeah, it still works

**Comment by checkplys** [comment]
Got it working :) But there's no pokemons showing, I can only see pokemons when they enter my "radius". And this dropped my 164 pokeballs, anyway to disable the "only 100 pokeballs".

**Comment by checkplys** [comment]
Also, there's a clearify on  my screen for around 5 minutes, and the bot didn't catch it yet. I have the bot mode in all.

**Comment by checkplys** [comment]
in trackemon.com (Still working pokemon tracker) there's no clearify there O.o

**Comment by sniok** [comment]
@checkplys Only nearby pokemon showing is expected behaviour. 
Dropping option is not supported yet in desktop ui, you can edit gofbot/configs/config.json though
