### ISSUE TITLE
Pre-built bot stops working after a few moments

### ISSUE THREAD

**Issue by akatechis** [PokemonGoF/PokemonGo-Bot-Desktop#54]
I can get it to work if I log out and back in again, but I constantly get the same error (ending in a list index error). From the devtools:

Failed to load resource: net::ERR_FILE_NOT_FOUND
main.html:107 [20:54:41]  PokemonGO Bot v1.0 

main.html:107 [20:54:41]  No config argument specified, checking for /configs/config.json 

main.html:107 [20:54:41]  Configuration initialized 

main.html:107 [20:54:41] [x] Coordinates found in passed in location, not geocoding.
[20:54:41] 
[20:54:41] Location Found: 40.7644429,-73.967036
main.html:107 
[20:54:41] GeoPosition: (40.7644429, -73.967036, 0)
[20:54:41] 
[20:54:41] [x] Parsing cached location...

main.html:107 [20:54:41] 
[20:54:41] [x] Last location flag used. Overriding passed in location
[20:54:41] [x] Last in-game location was set as: (40.764405879319064, -73.9670753577657, 0)

main.html:107 [20:54:41] 
[20:54:41] Attempting login to Pokemon Go.

main.html:98 server up
main.html:165 Error: Cannot call loadURL because the webContents is unavailable. The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.(…)
main.html:112 server started!
main.html:98 server up
2main.html:134 
main.html:86 Error getting location, trying second provider PositionError
main.html:88 Found location [40.7517,-73.8832] by ipinfo.io
main.html:134 about:blank
main.html:107 [20:54:42]  Login to Pokemon Go successful. 

3main.html:138 Loaded pokemon data..
main.html:107 [20:54:43] 
[20:54:43]  --- NAME --- 
[20:54:43]  Level: 11 (Next Level: 6950 XP) (Total: 58050 XP) 
[20:54:43]  Pokemon Captured: 236 | Pokestops Visited: 211 
main.html:107 
[20:54:43]  Pokemon Bag: 106/250 
[20:54:43]  Items: 166/350 
[20:54:43]  Stardust: 27209 | Pokecoins: 0 
[20:54:43]  PokeBalls: 69 | GreatBalls: 0 | UltraBalls: 0 

main.html:107 [20:54:43]  RazzBerries: 51 | BlukBerries: 0 | NanabBerries: 0 
[20:54:43]  LuckyEgg: 1 | Incubator: 2 | TroyDisk: 2 
[20:54:43]  Potion: 8 | SuperPotion: 20 | HyperPotion: 0 
[20:54:43]  Incense: 0 | IncenseSpicy: 0 | IncenseCool: 0 
[20:54:43]  Revive: 11 | MaxRevive: 0 

main.html:107 [20:54:43] 
[20:54:43] 

main.html:107 [20:54:43]  Server seems to be busy or offline - try again - 1/5 

main.html:107 [20:54:47]  Starting PokemonGo Bot.... 

3main.html:138 Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys
3main.html:138 Google Maps API warning: InvalidKey https://developers.google.com/maps/documentation/javascript/error-messages#invalid-key
main.html:107 [20:54:47]  [x] Next egg incubates in 0.75 km 

main.html:107 [20:54:48] Using lucky egg ... you have 1

main.html:107 [20:54:49] Walking from (40.764405879319064, -73.9670753577657) to [40.764405879319064, -73.9670753577657] 0.00km

main.html:107 [20:54:50] Something rustles nearby!

main.html:107 [20:54:50]  A Wild Pidgey appeared! [CP 146] [Potential 0.47] 
[20:54:50] IV [Stamina/Attack/Defense] = [5/5/11]

main.html:107 [20:54:53] Using Pokeball (chance: 50.05%)... (68 left!)

main.html:107 [20:54:54]  [-] Attempted to capture Pidgey - failed.. trying again! 

main.html:107 [20:54:56] Using Pokeball (chance: 50.05%)... (67 left!)

main.html:107 [20:54:57]  Captured Pidgey! [CP 146] [Potential 0.47] [5/5/11] [+220 exp] 

main.html:107 [20:55:02] Lured pokemon at fort 2894b9d6558d4c9daf6e0fb3a87b0189.16

main.html:107 [20:55:02]  A Wild Squirtle appeared! [CP 220] [Potential 0.49] 
[20:55:02] IV [Stamina/Attack/Defense] = [13/0/9]

main.html:107 [20:55:05] Catch Rate with normal Pokeball is low (20.02%). Thinking to throw a Razz Berry... (50 left!)

main.html:107 [20:55:06] Threw a berry! Catch Rate with normal Pokeball has increased to 30.03%
[20:55:06] Using Pokeball (chance: 30.03%)... (68 left!)

main.html:107 [20:55:06]  Captured Squirtle! [CP 220] [Potential 0.49] [13/0/9] [+220 exp] 

main.html:107 [20:55:11]  Now at Pokestop: The Lace Building 
[20:55:11]  Spinning ... 

main.html:107 [20:55:12]  Loot:  
[20:55:12]  100 xp 

main.html:107 [20:55:12]  - 3x Pokeball (Total: 69) 

main.html:107 [20:55:12]  - 1x Razz Berry (Total: 51) 
[20:55:12] PokeStop on cooldown. Time left: 5 minutes, 6 seconds

main.html:107 [20:55:14] Arrived at pokestop.
[20:55:14] Walking from (40.764405879319064, -73.9670753577657) to [40.764405879319064, -73.9670753577657] 0.00km

main.html:107 [20:55:16]  Now at Pokestop: Upper East Side Historic District 
[20:55:16]  Spinning ... 

main.html:107 [20:55:16]  Loot:  
[20:55:16]  100 xp 

main.html:107 [20:55:17]  - 1x Revive (Total: 12) 
[20:55:17]  - 2x Razz Berry (Total: 53) 
main.html:107 
[20:55:17]  - 1x Pokeball (Total: 70) 

main.html:107 [20:55:17] PokeStop on cooldown. Time left: 5 minutes, 6 seconds

main.html:107 [20:55:19] Moving towards fort Society of Illustrators Inc., 0.05km left

main.html:107 [20:55:24] 
[20:55:24]  Ran for 0:00:43 
[20:55:24]  Total XP Earned: 640  Average: 54165.88/h 
[20:55:24]  Travelled 0.00km 

main.html:107 [20:55:24]  Visited 2 stops 
[20:55:24]  Encountered 2 pokemon, 2 caught, 0 released, 0 evolved, 0 never seen before 
[20:55:24]  Threw 3 pokeballs 
[20:55:24]  Earned 200 Stardust 
[20:55:24] 
[20:55:24]  Highest CP Pokemon: Squirtle [CP: 220] [IV: 13/0/9] Potential: 0.49  
[20:55:24]  Most Perfect Pokemon: Squirtle [CP: 220] [IV: 13/0/9] Potential: 0.49  

main.html:107 Traceback (most recent call last):
  File "./pokecli.py", line 495, in <module>

main.html:107     main()
  File "./pokecli.py", line 71, in main

main.html:107     bot.tick()
  File "C:\pikabot\PikaBot-win32-ia32\resources\app\gofbot\pokemongo_bot__init__.py", line 85, in tick

main.html:107     if worker.work() == WorkerResult.RUNNING:
  File "C:\pikabot\PikaBot-win32-ia32\resources\app\gofbot\pokemongo_bot\cell_workers\follow_spiral.py", line 56, in work

main.html:107     point = self.points[self.ptr]
IndexError: list index out of range

**Comment by geoah** [comment]
Add a number for `max steps` and it should work.

Related issue https://github.com/PokemonGoF/PokemonGo-Bot-Desktop/issues/55

**Comment by akatechis** [comment]
That fixed it for me. I suppose the issue is with the default value not being used for some reason?
