### ISSUE TITLE
Error after npm install cannot start anything...

### ISSUE THREAD

**Issue by Shinoby1992** [PokemonGoF/PokemonGo-Bot-Desktop#57]
Found existing installation: protobuf 2.6.1
    Uninstalling protobuf-2.6.1:
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 736, in install
    requirement.uninstall(auto_confirm=True)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 742, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/usr/local/lib/python2.7/site-packages/pip/utils/**init**.py", line 267, in renames
    shutil.move(old, new)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 303, in move
    os.unlink(src)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/site-packages/google/protobuf/**init**.py'

**Comment by justinbeatz** [comment]
Error is clear **OSError: [Errno 13] Permission denied** are you doing sudo npm install ?

**Comment by sniok** [comment]
This is permission issue. Try running `sudo npm install` or `sudo pip install -r requirements.txt` in gofbot folder.
