### ISSUE TITLE
Javascript Error: ENOENT:

### ISSUE THREAD

**Issue by Bilters** [PokemonGoF/PokemonGo-Bot-Desktop#69]
### Expected Behavior

To launch the application.
### Actual Behavior

Pop up showing Javascript error

```
Uncaught Exception:
Error: ENOENT: no such file or directory, rename '/Users/bilters/Desktop/POKEMON/PokemonGo-Bot-Desktop/gofbot/web/userdata.js.example' -> '/Users/bilters/Desktop/POKEMON/PokemonGo-Bot-Desktop/gofbot/web/userdata.js'
    at Error (native)
    at Object.fs.renameSync (fs.js:809:18)
    at startPython (/Users/bilters/Desktop/POKEMON/PokemonGo-Bot-Desktop/main.js:193:8)
    at EventEmitter.<anonymous> (/Users/bilters/Desktop/POKEMON/PokemonGo-Bot-Desktop/main.js:118:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/Users/bilters/Desktop/POKEMON/PokemonGo-Bot-Desktop/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:209:13)
    at emitTwo (events.js:106:13)a
    at WebContents.emit (events.js:191:7)
```
### Steps to Reproduce

Launching the complete new pull. (Did a complete wipe and reinstall of this repository)

**Comment by t-v** [comment]
I can confirm this error

**Comment by nseckinoral** [comment]
1. Navigate to gofbot/web/config
2. Copy userdata.js.example
3. Paste into gofbot/web
4. Rename it to "userdata.js"
   5.Profit????

If no one else creates a PR, I'll try to send one tonight (just got off plane too tired atm). I'm not sure if it's the right way to fix it for devs though. By reading the Error message and the Readme file in gofbot/web I think it was intended to be there, not in /config.

**Comment by sniok** [comment]
8bf9dc9 should fix it

**Comment by sniok** [comment]
@nseckinoral We can't modify gofbot folder or web folder because they are seaprate submodules

**Comment by nseckinoral** [comment]
Sorry for sticking my nose 😅  I was trying to help till it gets fixed officially. Thanks for the fast patch! Highly appreciate your work. @sniok

**Comment by jhello23** [comment]
i try it and the map cannot load due to java error

**Comment by sniok** [comment]
@jhello23 please post error text

**Comment by jhello23** [comment]
@sniok "This page didn't load Google Maps correctly. See the JavaScript Console for technical details" . is this only the prob to my java ? need to update it ?

**Comment by jhello23** [comment]
here is the image [http://imgur.com/a/lCa4n](url)

**Comment by jhello23** [comment]
http://imgur.com/a/lCa4n  this is the image . @sniok

**Comment by sniok** [comment]
@jhello23 You are using old version that doesn't work. Wait until new release or try build from source.

**Comment by siembz** [comment]
You have to enable java on google api

**Comment by cezarsmpio** [comment]
Still it happens

```
Uncaught Exception:
Error: ENOENT: no such file or directory, rename '/Users/cezar/Documents/PokemonGo-Bot-Desktop/build/gofbot/web/config/userdata.js.example' -> '/Users/cezar/Documents/PokemonGo-Bot-Desktop/build/gofbot/web/config/userdata.js'
    at Error (native)
    at Object.fs.renameSync (fs.js:809:18)
    at startPython (/Users/cezar/Documents/PokemonGo-Bot-Desktop/build/app.js:195:8)
    at EventEmitter.<anonymous> (/Users/cezar/Documents/PokemonGo-Bot-Desktop/build/app.js:114:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/Users/cezar/Documents/PokemonGo-Bot-Desktop/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:209:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
```

**Comment by adrianoresende** [comment]
Same here, i have file userdata.js in `/build/gofbot/web/config/` but not work

Check prints:
0.0.1-alpha or 0.0.2-alpha ?????
![image](https://cloud.githubusercontent.com/assets/798755/17607329/870a086e-5ffb-11e6-8c3c-461ff15d8b9a.png)

![image](https://cloud.githubusercontent.com/assets/798755/17607304/59f30722-5ffb-11e6-838f-d49c719fff03.png)

**Comment by viet241** [comment]
same issue :(

**Comment by vincentcsm** [comment]
try get # permission
cd gofbot
virtualenv .
set bin/activate
pip install -r requirement.txt
npm install
run with # npm start

**Comment by Corecrafts** [comment]
did it work properly?
