### ISSUE TITLE
After running the PokemonGo-Bot-Desktop, it just nothing happen

### ISSUE THREAD

**Issue by spdragon** [PokemonGoF/PokemonGo-Bot-Desktop#78]
![problem4](https://cloud.githubusercontent.com/assets/20884593/17462871/75eb7728-5cec-11e6-94f5-39deaa4e4d73.jpg)
![problem3](https://cloud.githubusercontent.com/assets/20884593/17462872/761db8b4-5cec-11e6-8042-497d1e4deeea.jpg)

it just show the pikabot and nothing happen, doesn't seem like any bot working

**Comment by sniok** [comment]
Seems like bot isn't starting.  
Go to gofbot folder and try running `python pokecli.py -cf configs/config.json` and post output here

**Comment by spdragon** [comment]
`  File "c:\python27\Lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "c:\python27\Lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "c:\python27\Lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "c:\python27\Lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "c:\python27\Lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "c:\python27\Lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "c:\python27\Lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "c:\python27\Lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "c:\python27\Lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "c:\python27\Lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "c:\python27\Lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "c:\python27\Lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "c:\python27\Lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "c:\python27\Lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "c:\python27\Lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "c:\python27\Lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "c:\python27\Lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "c:\python27\Lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "c:\python27\Lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "c:\python27\Lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "c:\python27\Lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "c:\python27\Lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "c:\python27\Lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "c:\python27\Lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "c:\python27\Lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "c:\python27\Lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "c:\python27\Lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "c:\python27\Lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "c:\python27\Lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "c:\python27\Lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "c:\python27\Lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "c:\python27\Lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "c:\python27\Lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "c:\python27\Lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "c:\python27\Lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "c:\python27\Lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "c:\python27\Lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "c:\python27\Lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "c:\python27\Lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "c:\python27\Lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "c:\python27\Lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "c:\python27\Lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "c:\python27\Lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "c:\python27\Lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "c:\python27\Lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "c:\python27\Lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "c:\python27\Lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "c:\python27\Lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "c:\python27\Lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "c:\python27\Lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "c:\python27\Lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "c:\python27\Lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "c:\python27\Lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "c:\python27\Lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "c:\python27\Lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "c:\python27\Lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "c:\python27\Lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "c:\python27\Lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "c:\python27\Lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "c:\python27\Lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "c:\python27\Lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "c:\python27\Lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "c:\python27\Lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "c:\python27\Lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
RuntimeError: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 127, in main
    report_summary(bot)
  File "pokecli.py", line 136, in report_summary
    metrics.capture_stats()
  File "C:\Users\User-PC\Documents\PokemonGo-Bot-Desktop-development\PokemonGo-B
ot-Desktop\gofbot\pokemongo_bot\metrics.py", line 76, in capture_stats
    response_dict = request.call()
  File "C:\Users\User-PC\Documents\PokemonGo-Bot-Desktop-development\PokemonGo-B
ot-Desktop\gofbot\pokemongo_bot\api_wrapper.py", line 106, in call
    result = self._call()
  File "C:\Users\User-PC\Documents\PokemonGo-Bot-Desktop-development\PokemonGo-B
ot-Desktop\gofbot\pokemongo_bot\api_wrapper.py", line 63, in _call
    return PGoApiRequest.call(self)
  File "c:\users\user-pc\documents\pokemongo-bot-master\src\pgoapi\pgoapi\pgoapi
.py", line 210, in call
    request.activate_signature(lib_path)
  File "c:\users\user-pc\documents\pokemongo-bot-master\src\pgoapi\pgoapi\rpc_ap
i.py", line 85, in activate_signature
    self._signature_lib = ctypes.cdll.LoadLibrary(lib_path)
  File "c:\python27\Lib\ctypes\__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "c:\python27\Lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2016-08-07 22:27:09,548 [sentry.errors] [ERROR] Sentry responded with an error:
'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (u
rl: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "C:\Users\User-PC\Documents\PokemonGo-Bot-master\lib\site-packages\raven\
transport\threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "C:\Users\User-PC\Documents\PokemonGo-Bot-master\lib\site-packages\raven\
transport\http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "C:\Users\User-PC\Documents\PokemonGo-Bot-master\lib\site-packages\raven\
utils\http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\User-PC\Documents\PokemonGo-Bot-master\lib\site-packages\future
\backports\urllib\request.py", line 494, in open
    response = self._open(req, data)
  File "C:\Users\User-PC\Documents\PokemonGo-Bot-master\lib\site-packages\future
\backports\urllib\request.py", line 512, in _open
    '_open', req)
  File "C:\Users\User-PC\Documents\PokemonGo-Bot-master\lib\site-packages\future
\backports\urllib\request.py", line 466, in _call_chain
    result = func(*args)
  File "C:\Users\User-PC\Documents\PokemonGo-Bot-master\lib\site-packages\raven\
utils\http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "C:\Users\User-PC\Documents\PokemonGo-Bot-master\lib\site-packages\future
\backports\urllib\request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "c:\python27\Lib\httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "c:\python27\Lib\httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "c:\python27\Lib\httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "c:\python27\Lib\httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal
not in range(128)
2016-08-07 22:27:09,632 [sentry.errors.uncaught] [ERROR] [u'WindowsError: [Error
 126] The specified module could not be found', u'  File "pokecli.py", line 493,
 in <module>', u'  File "pokecli.py", line 127, in main', u'  File "pokecli.py",
 line 136, in report_summary', u'  File "C:\\Users\\User-PC\\Documents\\PokemonG
o-Bot-Desktop-development\\PokemonGo-Bot-Desktop\\gofbot\\pokemongo_bot\\metrics
.py", line 76, in capture_stats', u'  File "C:\\Users\\User-PC\\Documents\\Pokem
onGo-Bot-Desktop-development\\PokemonGo-Bot-Desktop\\gofbot\\pokemongo_bot\\api_
wrapper.py", line 106, in call', u'  File "C:\\Users\\User-PC\\Documents\\Pokemo
nGo-Bot-Desktop-development\\PokemonGo-Bot-Desktop\\gofbot\\pokemongo_bot\\api_w
rapper.py", line 63, in _call', u'  File "c:\\users\\user-pc\\documents\\pokemon
go-bot-master\\src\\pgoapi\\pgoapi\\pgoapi.py", line 210, in call', u'  File "c:
\\users\\user-pc\\documents\\pokemongo-bot-master\\src\\pgoapi\\pgoapi\\rpc_api.
py", line 85, in activate_signature', u'  File "c:\\python27\\Lib\\ctypes\\__ini
t__.py", line 440, in LoadLibrary', u'  File "c:\\python27\\Lib\\ctypes\\__init_
_.py", line 362, in __init__']

(PokemonGo-Bot-master) C:\Users\User-PC\Documents\PokemonGo-Bot-Desktop-developm
ent\PokemonGo-Bot-Desktop\gofbot>

(PokemonGo-Bot-master) C:\Users\User-PC\Documents\PokemonGo-Bot-Desktop-developm
ent\PokemonGo-Bot-Desktop\gofbot>python pokecli.py -cf configs/config.json
2016-08-07 22:28:07,190 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-07 22:28:07,200 [       cli] [INFO] Configuration initialized
2016-08-07 22:28:07,200 [pokemongo_bot.health_record.bot_event] [INFO] Health ch
eck is enabled. For more logrmation:
2016-08-07 22:28:07,201 [pokemongo_bot.health_record.bot_event] [INFO] https://g
ithub.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-08-07 22:28:07,223 [requests.packages.urllib3.connectionpool] [INFO] Starti
ng new HTTP connection (1): www.google-analytics.com
2016-08-07 22:28:37,513 [PokemonGoBot] [INFO] [set_start_location] Setting start
 location.
2016-08-07 22:28:37,515 [PokemonGoBot] [INFO] [x] Coordinates found in passed in
 location, not geocoding.
2016-08-07 22:28:37,516 [PokemonGoBot] [INFO] [location_found] Location found: 2
2.3193628,114.1589395 (22.3193628, 114.1589395, 0.0)
2016-08-07 22:28:37,516 [PokemonGoBot] [INFO] [position_update] Now at (22.31936
28, 114.1589395, 0)
2016-08-07 22:28:37,519 [PokemonGoBot] [INFO] [login_started] Login procedure st
arted.
Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 127, in main
    report_summary(bot)
  File "pokecli.py", line 136, in report_summary
    metrics.capture_stats()
  File "C:\Users\User-PC\Documents\PokemonGo-Bot-Desktop-development\PokemonGo-B
ot-Desktop\gofbot\pokemongo_bot\metrics.py", line 76, in capture_stats
    response_dict = request.call()
  File "C:\Users\User-PC\Documents\PokemonGo-Bot-Desktop-development\PokemonGo-B
ot-Desktop\gofbot\pokemongo_bot\api_wrapper.py", line 90, in call
    if not self.can_call():
  File "C:\Users\User-PC\Documents\PokemonGo-Bot-Desktop-development\PokemonGo-B
ot-Desktop\gofbot\pokemongo_bot\api_wrapper.py", line 58, in can_call
    raise NotLoggedInException()
pgoapi.exceptions.NotLoggedInException
2016-08-07 22:28:47,723 [sentry.errors] [ERROR] Sentry responded with an error:
'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (u
rl: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "C:\Users\User-PC\Documents\PokemonGo-Bot-master\lib\site-packages\raven\
transport\threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "C:\Users\User-PC\Documents\PokemonGo-Bot-master\lib\site-packages\raven\
transport\http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "C:\Users\User-PC\Documents\PokemonGo-Bot-master\lib\site-packages\raven\
utils\http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\User-PC\Documents\PokemonGo-Bot-master\lib\site-packages\future
\backports\urllib\request.py", line 494, in open
    response = self._open(req, data)
  File "C:\Users\User-PC\Documents\PokemonGo-Bot-master\lib\site-packages\future
\backports\urllib\request.py", line 512, in _open
    '_open', req)
  File "C:\Users\User-PC\Documents\PokemonGo-Bot-master\lib\site-packages\future
\backports\urllib\request.py", line 466, in _call_chain
    result = func(*args)
  File "C:\Users\User-PC\Documents\PokemonGo-Bot-master\lib\site-packages\raven\
utils\http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "C:\Users\User-PC\Documents\PokemonGo-Bot-master\lib\site-packages\future
\backports\urllib\request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "c:\python27\Lib\httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "c:\python27\Lib\httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "c:\python27\Lib\httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "c:\python27\Lib\httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal
not in range(128)
2016-08-07 22:28:47,736 [sentry.errors.uncaught] [ERROR] [u'NotLoggedInException
', u'  File "pokecli.py", line 493, in <module>', u'  File "pokecli.py", line 12
7, in main', u'  File "pokecli.py", line 136, in report_summary', u'  File "C:\\
Users\\User-PC\\Documents\\PokemonGo-Bot-Desktop-development\\PokemonGo-Bot-Desk
top\\gofbot\\pokemongo_bot\\metrics.py", line 76, in capture_stats', u'  File "C
:\\Users\\User-PC\\Documents\\PokemonGo-Bot-Desktop-development\\PokemonGo-Bot-D
esktop\\gofbot\\pokemongo_bot\\api_wrapper.py", line 90, in call', u'  File "C:\
\Users\\User-PC\\Documents\\PokemonGo-Bot-Desktop-development\\PokemonGo-Bot-Des
ktop\\gofbot\\pokemongo_bot\\api_wrapper.py", line 58, in can_call']`
it too long, i cannot capture all of it

**Comment by spdragon** [comment]
`
(PokemonGo-Bot-master) C:\Users\User-PC\Documents\PokemonGo-Bot-Desktop-developm
ent\PokemonGo-Bot-Desktop\gofbot>python pokecli.py -cf configs/config.json
2016-08-07 22:28:07,190 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-07 22:28:07,200 [       cli] [INFO] Configuration initialized
2016-08-07 22:28:07,200 [pokemongo_bot.health_record.bot_event] [INFO] Health ch
eck is enabled. For more logrmation:
2016-08-07 22:28:07,201 [pokemongo_bot.health_record.bot_event] [INFO] https://g
ithub.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-08-07 22:28:07,223 [requests.packages.urllib3.connectionpool] [INFO] Starti
ng new HTTP connection (1): www.google-analytics.com
2016-08-07 22:28:37,513 [PokemonGoBot] [INFO] [set_start_location] Setting start
 location.
2016-08-07 22:28:37,515 [PokemonGoBot] [INFO] [x] Coordinates found in passed in
 location, not geocoding.
2016-08-07 22:28:37,516 [PokemonGoBot] [INFO] [location_found] Location found: 2
2.3193628,114.1589395 (22.3193628, 114.1589395, 0.0)
2016-08-07 22:28:37,516 [PokemonGoBot] [INFO] [position_update] Now at (22.31936
28, 114.1589395, 0)
2016-08-07 22:28:37,519 [PokemonGoBot] [INFO] [login_started] Login procedure st
arted.
Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 127, in main
    report_summary(bot)
  File "pokecli.py", line 136, in report_summary
    metrics.capture_stats()
  File "C:\Users\User-PC\Documents\PokemonGo-Bot-Desktop-development\PokemonGo-B
ot-Desktop\gofbot\pokemongo_bot\metrics.py", line 76, in capture_stats
    response_dict = request.call()
  File "C:\Users\User-PC\Documents\PokemonGo-Bot-Desktop-development\PokemonGo-B
ot-Desktop\gofbot\pokemongo_bot\api_wrapper.py", line 90, in call
    if not self.can_call():
  File "C:\Users\User-PC\Documents\PokemonGo-Bot-Desktop-development\PokemonGo-B
ot-Desktop\gofbot\pokemongo_bot\api_wrapper.py", line 58, in can_call
    raise NotLoggedInException()
pgoapi.exceptions.NotLoggedInException
2016-08-07 22:28:47,723 [sentry.errors] [ERROR] Sentry responded with an error:
'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (u
rl: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "C:\Users\User-PC\Documents\PokemonGo-Bot-master\lib\site-packages\raven\
transport\threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "C:\Users\User-PC\Documents\PokemonGo-Bot-master\lib\site-packages\raven\
transport\http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "C:\Users\User-PC\Documents\PokemonGo-Bot-master\lib\site-packages\raven\
utils\http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\User-PC\Documents\PokemonGo-Bot-master\lib\site-packages\future
\backports\urllib\request.py", line 494, in open
    response = self._open(req, data)
  File "C:\Users\User-PC\Documents\PokemonGo-Bot-master\lib\site-packages\future
\backports\urllib\request.py", line 512, in _open
    '_open', req)
  File "C:\Users\User-PC\Documents\PokemonGo-Bot-master\lib\site-packages\future
\backports\urllib\request.py", line 466, in _call_chain
    result = func(*args)
  File "C:\Users\User-PC\Documents\PokemonGo-Bot-master\lib\site-packages\raven\
utils\http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "C:\Users\User-PC\Documents\PokemonGo-Bot-master\lib\site-packages\future
\backports\urllib\request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "c:\python27\Lib\httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "c:\python27\Lib\httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "c:\python27\Lib\httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "c:\python27\Lib\httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal
not in range(128)
2016-08-07 22:28:47,736 [sentry.errors.uncaught] [ERROR] [u'NotLoggedInException
', u'  File "pokecli.py", line 493, in <module>', u'  File "pokecli.py", line 12
7, in main', u'  File "pokecli.py", line 136, in report_summary', u'  File "C:\\
Users\\User-PC\\Documents\\PokemonGo-Bot-Desktop-development\\PokemonGo-Bot-Desk
top\\gofbot\\pokemongo_bot\\metrics.py", line 76, in capture_stats', u'  File "C
:\\Users\\User-PC\\Documents\\PokemonGo-Bot-Desktop-development\\PokemonGo-Bot-D
esktop\\gofbot\\pokemongo_bot\\api_wrapper.py", line 90, in call', u'  File "C:\
\Users\\User-PC\\Documents\\PokemonGo-Bot-Desktop-development\\PokemonGo-Bot-Des
ktop\\gofbot\\pokemongo_bot\\api_wrapper.py", line 58, in can_call']`

**Comment by spdragon** [comment]
(PokemonGo-Bot-master) C:\Users\User-PC\Documents\PokemonGo-Bot-Desktop-developm
ent\PokemonGo-Bot-Desktop\gofbot>python pokecli.py -cf configs/config.json
2016-08-07 22:28:07,190 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-07 22:28:07,200 [       cli] [INFO] Configuration initialized
2016-08-07 22:28:07,200 [pokemongo_bot.health_record.bot_event] [INFO] Health ch
eck is enabled. For more logrmation:
2016-08-07 22:28:07,201 [pokemongo_bot.health_record.bot_event] [INFO] https://g
ithub.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-08-07 22:28:07,223 [requests.packages.urllib3.connectionpool] [INFO] Starti
ng new HTTP connection (1): www.google-analytics.com
2016-08-07 22:28:37,513 [PokemonGoBot] [INFO] [set_start_location] Setting start
 location.
2016-08-07 22:28:37,515 [PokemonGoBot] [INFO] [x] Coordinates found in passed in
 location, not geocoding.
2016-08-07 22:28:37,516 [PokemonGoBot] [INFO] [location_found] Location found: 2
2.3193628,114.1589395 (22.3193628, 114.1589395, 0.0)
2016-08-07 22:28:37,516 [PokemonGoBot] [INFO] [position_update] Now at (22.31936
28, 114.1589395, 0)
2016-08-07 22:28:37,519 [PokemonGoBot] [INFO] [login_started] Login procedure st
arted.
Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 127, in main
    report_summary(bot)
  File "pokecli.py", line 136, in report_summary
    metrics.capture_stats()
  File "C:\Users\User-PC\Documents\PokemonGo-Bot-Desktop-development\PokemonGo-B
ot-Desktop\gofbot\pokemongo_bot\metrics.py", line 76, in capture_stats
    response_dict = request.call()
  File "C:\Users\User-PC\Documents\PokemonGo-Bot-Desktop-development\PokemonGo-B
ot-Desktop\gofbot\pokemongo_bot\api_wrapper.py", line 90, in call
    if not self.can_call():
  File "C:\Users\User-PC\Documents\PokemonGo-Bot-Desktop-development\PokemonGo-B
ot-Desktop\gofbot\pokemongo_bot\api_wrapper.py", line 58, in can_call
    raise NotLoggedInException()
pgoapi.exceptions.NotLoggedInException
2016-08-07 22:28:47,723 [sentry.errors] [ERROR] Sentry responded with an error:
'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (u
rl: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "C:\Users\User-PC\Documents\PokemonGo-Bot-master\lib\site-packages\raven\
transport\threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "C:\Users\User-PC\Documents\PokemonGo-Bot-master\lib\site-packages\raven\
transport\http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "C:\Users\User-PC\Documents\PokemonGo-Bot-master\lib\site-packages\raven\
utils\http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\User-PC\Documents\PokemonGo-Bot-master\lib\site-packages\future
\backports\urllib\request.py", line 494, in open
    response = self._open(req, data)
  File "C:\Users\User-PC\Documents\PokemonGo-Bot-master\lib\site-packages\future
\backports\urllib\request.py", line 512, in _open
    '_open', req)
  File "C:\Users\User-PC\Documents\PokemonGo-Bot-master\lib\site-packages\future
\backports\urllib\request.py", line 466, in _call_chain
    result = func(*args)
  File "C:\Users\User-PC\Documents\PokemonGo-Bot-master\lib\site-packages\raven\
utils\http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "C:\Users\User-PC\Documents\PokemonGo-Bot-master\lib\site-packages\future
\backports\urllib\request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "c:\python27\Lib\httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "c:\python27\Lib\httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "c:\python27\Lib\httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "c:\python27\Lib\httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal
not in range(128)
2016-08-07 22:28:47,736 [sentry.errors.uncaught] [ERROR] [u'NotLoggedInException
', u'  File "pokecli.py", line 493, in <module>', u'  File "pokecli.py", line 12
7, in main', u'  File "pokecli.py", line 136, in report_summary', u'  File "C:\
Users\User-PC\Documents\PokemonGo-Bot-Desktop-development\PokemonGo-Bot-Desk
top\gofbot\pokemongo_bot\metrics.py", line 76, in capture_stats', u'  File "C
:\Users\User-PC\Documents\PokemonGo-Bot-Desktop-development\PokemonGo-Bot-D
esktop\gofbot\pokemongo_bot\api_wrapper.py", line 90, in call', u'  File "C:\
\Users\User-PC\Documents\PokemonGo-Bot-Desktop-development\PokemonGo-Bot-Des
ktop\gofbot\pokemongo_bot\api_wrapper.py", line 58, in can_call']

**Comment by sniok** [comment]
This is bot error, so we wait until they fix it
https://github.com/PokemonGoF/PokemonGo-Bot/issues/2812

**Comment by spdragon** [comment]
Thanks for the reply, i wait for it then.

**Comment by tnsbm** [comment]
Please reopen if error still persists
