### ISSUE TITLE
Bot Stops 

### ISSUE THREAD

**Issue by ghost** [PokemonGoF/PokemonGo-Bot-Desktop#90]
```
Traceback (most recent call last):
  File "pokecli.py", line 502, in <module>
    main()
  File "pokecli.py", line 133, in main
    raise e
IndexError: list index out of range
2016-08-08 21:06:07,527 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/Users/USERNAME/Dev/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/Users/USERNAME/Dev/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/Users/USERNAME/Dev/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/USERNAME/Dev/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/Users/USERNAME/Dev/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/Users/USERNAME/Dev/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/Users/USERNAME/Dev/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/Users/USERNAME/Dev/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 891, in _send_output
    msg += message_body
```
### Actual Behavior

Bot Stops
### Steps to Reproduce

virtualenv .
source bin/activate
python pokecly.py
### Information
- OS X 10.11

**Comment by Magamar01** [comment]
Have the same problem and don't know how to fix. Only solution for me is to log out of bot and log back in to restart the process.

**Comment by sniok** [comment]
So you are running Python bot and then opening an issue on desktop porting project?
Please look at PokemonGo-Bot repo. This is a known problem. We will update submodule once it get fixed

**Comment by DerHelmrich** [comment]
@sniok I'm really sorry for that. Was on the wrong repos when I posted this issue. My fault.

**Comment by sniok** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/3176
